name: PerformanceCheck

on:
  pull_request:
    branches:
      - master

jobs:
  analyze-2-3:
    name: 2.18 to 3.18
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: runspired/version-performance@master
        with:
          build-control: false
          build-experiment: false
          control-dist: ./dist-2-18
          experiment-dist: ./dist-3-18
          regression-threshold: 25
          fidelity: high
          clean-after-analyze: false
  analyze-2-3-upgraded:
    name: 2.18 to Octane
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: runspired/version-performance@master
        with:
          build-control: false
          build-experiment: false
          control-dist: './dist-2-18'
          experiment-dist: './dist-3-18-upgraded'
          regression-threshold: 25
          fidelity: high
          clean-after-analyze: false
  analyze-PR:
    name: 2.18 to PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0      
      - uses: runspired/version-performance@master
        with:
          build-control: false
          control-dist: './dist-2-18'
          regression-threshold: 25
          fidelity: high
          clean-after-analyze: false